name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint
